In [7]:
import sys
sys.path.append('./Module')
from PickleSaveLoad import decompress_pickle, compressed_pickle

In [9]:
all_data = decompress_pickle("./training_testing_preprocessed.pbz2")

{'best_one_hot_oridnalOnTarget': {'column_in_order': Index(['Kendaraan_Rusak_Pernah', 'Kendaraan_Rusak_Tidak', 'Sudah_Asuransi_0',
         'Sudah_Asuransi_1', 'Tertarik_0', 'Tertarik_1'],
        dtype='object'),
  'Test': {'X': array([[1, 0, 1, 0],
          [0, 1, 0, 1],
          [0, 1, 0, 1],
          ...,
          [0, 1, 0, 1],
          [1, 0, 1, 0],
          [0, 1, 1, 0]], dtype=uint8),
   'y': array([0, 0, 0, ..., 0, 1, 0])},
  0: {'X_train': array([[1, 0, 1, 0],
          [0, 1, 1, 0],
          [0, 1, 0, 1],
          ...,
          [0, 1, 0, 1],
          [0, 1, 0, 1],
          [0, 1, 0, 1]], dtype=uint8),
   'X_test': array([[0, 1, 0, 1],
          [0, 1, 0, 1],
          [1, 0, 1, 0],
          ...,
          [1, 0, 1, 0],
          [1, 0, 1, 0],
          [0, 1, 0, 1]], dtype=uint8),
   'y_train': array([0, 0, 0, ..., 0, 0, 0]),
   'y_test': array([0, 0, 0, ..., 0, 0, 0])},
  1: {'X_train': array([[0, 1, 0, 1],
          [0, 1, 1, 0],
          [0, 1, 0, 1],
        

In [89]:
all_data.keys()

dict_keys(['best_one_hot_oridnalOnTarget', 'best_one_hot', 'all_one_hot', 'all_ordinal'])

In [90]:
X = all_data["best_one_hot_oridnalOnTarget"][1]["X_train"]
y = all_data["best_one_hot_oridnalOnTarget"][1]["y_train"]

In [91]:
z = X.astype('int')

In [75]:
z = np.array([[1,2],[3,4],[5,6]])

In [76]:
z

array([[1, 2],
       [3, 4],
       [5, 6]])

In [78]:
z[:,0]

array([1, 3, 5])

# Cara buat decision tree?
1. Information Gain? Entropy
2. Ambil Information Gain terbesar
3. Cek relatif ke target

In [115]:
import numpy as np
class DecisionTreeClassifier:
    
    data_shape = {}
    initial_node = None
    
    class Node:
        
        index_num = -1 # To save what index is used in this node
        index_already_used = None
        other_node = {} # This will be initialize with the labels on the data
        def __init__(self, X:np.array, y:np.array, index_already_used: np.array):
            
            pass
        
        def __information_gain_calc(self, X:np.array, y:np.array) -> np.array:
            pass
        
    
    def __init__(self):
        print("DecisionTreeClassifier initialize!")
        print("Made by Kaenova Mahendra Auditama")
        print("Now do a .fit() to create the decision tree")
    
    def fit(self, X: np.array, y: np.array):
        # Checking data
        if X.shape[0] != y.shape[0]:
            raise Exception("Bentuk (panjang) X dan y yang dimasukkan tidak serupa.")
        if len(y.shape) > 1:
            raise Exception("Bentuk y harus 1 dimensi")
        if (X.dtype != 'int'):
            print("Warning: Data X tidak berbentuk integer, akan dilakukan konversi ke int")
            X = X.astype('int')
        if (y.dtype != 'int'):
            print("Warning: Data y tidak berbentuk integer, akan dilakukan konversi ke int")
            y = y.astype('int')
        
        # Save Data shape  
        # Save data y
        self.data_shape["y"] = np.unique(y)
        # Save data x
        for i in range(len(X[0])):
            self.data_shape[i] = np.unique(X[:,i])
        
        print("Label yang ada:",self.data_shape)
        # Do fitting
        
        pass
    
    def score(self, X: np.array, y: np.array) -> float:
        # Check
        if self.initial_node == None:
            raise Exception("Tree belum dibangun, harap lakukan model.fit() terlebih dahulu")
        # Checking data
        if X.shape[0] != y.shape[0]:
            raise Exception("Bentuk (panjang) X dan y yang dimasukkan tidak serupa.")
        if len(y.shape) > 1:
            raise Exception("Bentuk y harus 1 dimensi")
        if (X.dtype != 'int'):
            print("Warning: Data X tidak berbentuk integer, akan dilakukan konversi ke int")
            X = X.astype('int')
        if (y.dtype != 'int'):
            print("Warning: Data y tidak berbentuk integer, akan dilakukan konversi ke int")
            y = y.astype('int')
        self._data_shape_check(X, y)
        
        # Do inferencing
        
        pass
    
    def predict(self, X: np.array) -> np.array:
        
        # Check
        if self.initial_node == None:
            raise Exception("Tree belum dibangun, harap lakukan model.fit() terlebih dahulu")
        self._data_shape_valid(X, None)
        
        # Do inferencing
        
        pass
    
    def _data_shape_check(self, X: np.array, y: np.array):
        # Check y
        if y != None:
            for i in np.unique(y):
                if i not in self.data_shape["y"]:
                    raise ValueError("Label y tidak sama dengan yang di fit")
        # Check X
        for i in range(len(X[0])):
            for j in np.unique(X[:,i]):
                if j not in self.data_shape[i]:
                    raise ValueError("Label X tidak sama dengan yang di fit")

In [116]:
a = np.array([[1,2,3],[4,5,6]])
a[:,:3]

array([[1, 2, 3],
       [4, 5, 6]])

In [117]:
model = DecisionTreeClassifier()

DecisionTreeClassifier initialize!
Made by Kaenova Mahendra Auditama
Now do a .fit() to create the decision tree


In [118]:
model.fit(X, y)

Label yang ada: {'y': array([0, 1]), 0: array([0, 1]), 1: array([0, 1]), 2: array([0, 1]), 3: array([0, 1])}
